version: '3.8'

services:
  fastapi:
    build:
      context: ./frontend/fast_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
     

  streamlit:
    build:
      context: ./frontend/streamlit_app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
